program: train.py
method: random
metric:
  goal: maximize
  name: meanAP
parameters:
  batch_size:
    value: 1
  image_dataset_path:
    value: /workspaces/keypoint-detection/test/test_dataset
  json_dataset_path:
    value: /workspaces/keypoint-detection/test/test_dataset/dataset.json
  keypoint_channel_max_keypoints:
    value: -1 -1
  keypoint_channels:
    value: corner_keypoints flap_corner_keypoints
  wandb_project:
    value: "your-wandb-project"
  wandb_entity:
    value: "your-wandb-username"
